apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:SkvGtaiAIuOk7dwFaJU3eZmeHLkVdjhLJZCJInL3yHoA7JfIdYdSmg==,iv:H3mhIkypvtu5kxSQdyaG1p+r2GE+T3QIkHfZMZpP/eU=,tag:ErCXLvLCpRkC5jonyk4rXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f55sgl9ayk3mfecrajq4elq29y4ktekge7mr8vczfn9xyu37pa5qwptwu0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNWDRVaFNPZHkwcVFWaFFD
            bUxNYjc3bGwrOHRZZFJJRG5iN3Vya0JmTlR3CmZ0TCs2RnNvc1JwVUowaCszbFZO
            b3FJQXY5Y2ZDL3RsenJ6cGszYXhITHMKLS0tIEdMOVJQcTlDWVp6R2h1M2ZWMU5n
            ZzFpVzhoOWtrRU1QelhQaFVabUc4UWsKcMmxPYKzRSgnPlgDqMHJN/heRDlwJaK3
            IcvO21XIZ85WcyHrFqP1A+5GYVciWT/BC6FXgfds5j1EIct2/jsByg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-02T20:39:24Z"
    mac: ENC[AES256_GCM,data:GFTvxcyfkdZIQpUtB1snySXLI5v8+FX/IInMCT9qG4BYxo51Ix0xBKdEx0PUbcKDtVzbXz59cbzvrad85sa11kqgZW3KsdaZe6VW21+s0URcrf+F47APcEuKduwLfb7ksSShLXSuPTxaCq72N67AfBowfAzJ8wTM+QODnTD97Ic=,iv:A5dbZepxaxn/r8vx6kLxKXgL9YhpA+5xR9OLpf4zEBA=,tag:gZqqNGyP+JyaGqg0PNRi6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
