---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rcon
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: rcon-secret
    template:
      engineVersion: v2
      data:
        RWA_PASSWORD: "{{ .RCON_PASSWORD }}"
  dataFrom:
    - extract:
        key: rcon
