# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app rcon
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: rcon-web-admin
      version: 1.1.0
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    image:
      repository: docker.io/itzg/rcon
      tag: 0.14.1-1@sha256:4bec01981dc95e14f54c243ced5db23591c67e5a63d474a3f4f8acda72ce5a28
    resources:
      requests:
        cpu: 500m
      limits:
        memory: 1Gi
    rconWeb:
      passwordExistingSecret: rcon-secret
      passwordKey: RCON_PASSWORD
    ingress:
      ingressClassName: internal
      enabled: true
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "rcon.${SECRET_DOMAIN}"
      hosts:
        - name: "rcon.${SECRET_DOMAIN}"
