# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: qbtools-secret
stringData:
  1password-credentials.json: ENC[AES256_GCM,data:fSBA2Vmh5v1WwrY8krGETU3GAIIzV1YV,iv:TgL5wRhPs4fj8CXzMzrjNABaWbUUKpbjmYkVqwzz2Ek=,tag:1ke95Id7Hzo24W8zdCxGfA==,type:str]
sops:
  age:
    - recipient: age1487fv3g48lmeznwxktqgvyzaj63hxxhts5mm4zlxvkhm82gcnfpsh2rkqa
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUzlWNjBOeUNyRHlDM0F0
        cUFQLzAvRkVJdHdwZ2Rvc2xaSDdra3oram1zCmxTMmNjNHRNY3psQkQ2VDd4TjlF
        QVVReWh2YkJKRkE1MzQ1NmpMbHZKRUUKLS0tIGFPcUlta2VDMFdBL0RZWCtHamov
        QitwdXIvV3Y5K21BLzg2NXRGTE95UFUKnzQpr2zY1d9r7lzqMt/G6tWydPodL/yZ
        cMCYUb4cEKSGB0f5nK37gvWN8qVevXuGGj6XLA7I7w/ZB5JulhD29w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-04T04:30:12Z"
  mac: ENC[AES256_GCM,data:XxQMlp8uaNuCdtmtz1JULs31z2WqK8RFEG0Bjpj+TgZTe9Gg0bb4GSWYoPfgVgJHJ/Qshy8V141Avod4TRcMxecahaIqQI5jp0ApvfFh44g+DrSVxlxBc2NzZlvhCf37UHiIEHO8z0AU5OFDuDFZUwkjuSrnG8mRpLKGI6T0Qzs=,iv:sf6IKgDBDKLcwCZqK4E3PwTKL3jsY+OHP0sYhrReQbc=,tag:46eo8OULz8kY/r2qPVr6GQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
