---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/operator.victoriametrics.com/vmpodscrape_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: node-feature-discovery
spec:
  namespaceSelector:
    matchNames:
      - "system"
  selector:
    matchLabels:
      app.kubernetes.io/name: node-feature-discovery
      app.kubernetes.io/instance: node-feature-discovery
  podMetricsEndpoints:
    - port: http
      path: /metrics
      scheme: http
      interval: 10s
      honorLabels: true
