---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  POSTGRES_TASK_RESOURCES_DIR: "{{.ROOT_DIR}}/.taskfiles/postgres/resources"

tasks:
  backup:
    desc: Perform manual backup of a postgres db [NS=database] [CLUSTER=postgres16]
    preconditions:
      - which kubectl minijinja-cli
      - test -f "{{.POSTGRES_TASK_RESOURCES_DIR}}/backup.yaml.j2"
      - kubectl --namespace {{.NS}} get cluster {{.CLUSTER}}
    vars:
      NS: '{{.NS | default "database"}}'
      CLUSTER: '{{.CLUSTER | default "postgres16"}}'
      JOB: "{{.CLUSTER}}-manual"
    env:
      NS: "{{.NS}}"
      CLUSTER: "{{.CLUSTER}}"
    cmds:
      - minijinja-cli {{.POSTGRES_TASK_RESOURCES_DIR}}/backup.yaml.j2 | kubectl apply --server-side --filename -
      - until kubectl --namespace {{.NS}} get backup/{{.JOB}} &>/dev/null; do sleep 5; done
      - kubectl --namespace {{.NS}} wait backup/{{.JOB}} --for=jsonpath='{.status.phase}'=completed --timeout=5m
      - kubectl --namespace {{.NS}} delete backup/{{.JOB}}
