---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname paperless
  namespace: &namespace self-hosted
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 30m
  timeout: 5m
  path: "./kubernetes/apps/self-hosted/paperless/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  dependsOn:
    - name: dragonfly-cluster
      namespace: database
    - name: onepassword-store
      namespace: external-secrets
    - name: volsync
      namespace: volsync-system
    - name: keda
      namespace: system
  postBuild:
    substitute:
      APP: *appname
      VOLSYNC_CAPACITY: 15Gi
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
