---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open-telemetry-gateway-collector
rules:
  - apiGroups:
      - ""
    resources:
      - events
      - namespaces
      - namespaces/status
      - nodes
      - nodes/spec
      - pods
      - pods/status
      - replicationcontrollersc
      - replicationcontrollers/status
      - resourcequotas
      - services
      - "nodes"
    verbs:
      - "get"
      - "watch"
      - "list"
  - apiGroups:
      - "apps"
    resources:
      - "replicasets"
      - "deployments"
      - "statefulsets"
      - "daemonsets"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "batch"
    resources:
      - jobs
      - cronjobs
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "extensions"
    resources:
      - daemonsets
      - deployments
      - replicasets
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: open-telemetry-gateway-collector-binding
subjects:
  - kind: ServiceAccount
    name: open-telemetry-gateway-collector
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: open-telemetry-gateway-collector
  apiGroup: rbac.authorization.k8s.io
