---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open-telemetry-agent-collector
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "namespaces"
      - "nodes"
    verbs:
      - "get"
      - "watch"
      - "list"
  - apiGroups:
      - "apps"
    resources:
      - "replicasets"
      - "deployments"
      - "statefulsets"
      - "daemonsets"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "batch"
    resources:
      - "jobs"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "extensions"
    resources:
      - "replicasets"
    verbs:
      - "get"
      - "list"
      - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: open-telemetry-agent-collector-binding
subjects:
  - kind: ServiceAccount
    name: open-telemetry-agent-collector
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: open-telemetry-agent-collector
  apiGroup: rbac.authorization.k8s.io
