---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open-telemetry-agent-targetallocator
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/metrics
      - services
      - endpoints
      - pods
      - namespaces
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - "get"
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
      - podmonitors
      - probes
      - scrapeconfigs
    verbs:
      - '*'
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - "get"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: open-telemetry-agent-targetallocator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-telemetry-agent-targetallocator
subjects:
  - kind: ServiceAccount
    name: open-telemetry-agent-targetallocator
    namespace: monitoring
