---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./clusterrole-agent.yaml
  - ./clusterrole-gateway.yaml
  - ./clusterrole-ta.yaml
  - ./otel-agent.yaml
  - ./otel-gateway.yaml

