---
# yaml-language-server: $schema=https://kubernetes-schemas.jacob-williams.me/opentelemetry.io/opentelemetrycollector_v1beta1.json
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: open-telemetry-gateway
  namespace: monitoring
spec:
  mode: deployment
  config:
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      k8s_cluster:
        allocatable_types_to_report:
          - cpu
          - memory
        collection_interval: 30s
        metrics:
          k8s.node.condition:
            enabled: true
          k8s.pod.status_reason:
            enabled: true
        node_conditions_to_report:
          - Ready
          - MemoryPressure
          - DiskPressure
          - PIDPressure
          - NetworkUnavailable
        resource_attributes:
          container.runtime:
            enabled: true
          container.runtime.version:
            enabled: true
          k8s.container.status.last_terminated_reason:
            enabled: true
          k8s.kubelet.version:
            enabled: true
          k8s.pod.qos_class:
            enabled: true

    exporters:
      otlphttp/victoriametrics:
        endpoint: http://vmsingle-metrics.monitoring.svc.cluster.local:8428/opentelemetry

      otlphttp/victorialogs:
        endpoint: http://vlsingle-logs.monitoring:9428/insert/opentelemetry

      # otlphttp/victoriatraces:
      #   endpoint: http://vtsingle-traces.monitoring:9428/insert/opentelemetry

    processors:
      batch:
      memory_limiter:
        check_interval: 1s
        limit_mib: 400
        spike_limit_mib: 100
      k8sattributes:
        extract:
          metadata:
            - k8s.namespace.name
            - k8s.deployment.name
            - k8s.statefulset.name
            - k8s.daemonset.name
            - k8s.cronjob.name
            - k8s.job.name
            - k8s.node.name
            - k8s.node.uid
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.pod.start_time
        passthrough: false
        pod_association:
          - sources:
              - from: resource_attribute
                name: k8s.pod.ip
          - sources:
              - from: resource_attribute
                name: k8s.pod.uid
          - sources:
              - from: connection

    service:
      pipelines:
        metrics:
          receivers:
            - k8s_cluster
            - otlp
          processors:
            - k8sattributes
            - memory_limiter
            - batch
          exporters:
            - otlphttp/victoriametrics
        logs:
          receivers:
            - k8s_cluster
            - otlp
          processors:
            - k8sattributes
            - memory_limiter
            - batch
          exporters:
            - otlphttp/victorialogs
          # traces:
          #   receivers:
          #     - otlp
          #   processors:
          #     - memory_limiter
          #     - batch
          #   exporters:
          #     - otlphttp/victoriatraces
