---
# yaml-language-server: $schema=https://kubernetes-schemas.jacob-williams.me/opentelemetry.io/opentelemetrycollector_v1beta1.json
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: open-telemetry-agent
  namespace: monitoring
spec:
  mode: daemonset
  targetAllocator:
    enabled: true
    allocationStrategy: per-node
    prometheusCR:
      enabled: true
      podMonitorSelector: {}
      serviceMonitorSelector: {}
  env:
    - name: K8S_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
  config:
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      prometheus:
        trim_metric_suffixes: true
        config:
          scrape_configs:
            - job_name: 'otel-collector'
              scrape_interval: 10s
              static_configs:
                - targets:
                    - '0.0.0.0:8888'
              bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              tls_config:
                ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                insecure_skip_verify: true

    exporters:
      otlp:
        endpoint: open-telemetry-gateway-collector.monitoring.svc.cluster.local:4317
        tls:
          insecure: true

    processors:
      batch:

    service:
      pipelines:
        metrics:
          receivers:
            - prometheus
            - otlp
          processors:
            - batch
          exporters:
            - otlp
