---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-agent
  namespace: monitoring
spec:
  mode: daemonset
  targetAllocator:
    enabled: true
    allocationStrategy: per-node
    prometheusCR:
      enabled: true
      podMonitorSelector: {}
      serviceMonitorSelector: {}
  config:
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      prometheus:
        trim_metric_suffixes: true
        config:
          scrape_configs:
            - job_name: 'otel-collector'
              scrape_interval: 10s
              static_configs:
                - targets:
                    - '0.0.0.0:8888'

    exporters:
      otlp:
        endpoint: open-telemetry-gateway-collector.monitoring.svc.cluster.local:4317
        tls:
          insecure: true

    processors:
      batch:

    service:
      pipelines:
        metrics:
          receivers:
            - prometheus
            - otlp
          processors:
            - batch
          exporters:
            - otlp
