---
# yaml-language-server: $schema=https://kubernetes-schemas.jacob-williams.me/opentelemetry.io/opentelemetrycollector_v1beta1.json
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: open-telemetry-gateway
  namespace: monitoring
spec:
  mode: deployment
  env:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: K8S_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: K8S_NODE_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
  config:
    extensions:
      health_check:
        endpoint: ${env:MY_POD_IP}:13133

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            endpoint: ${env:MY_POD_IP}:4318
      k8s_cluster:
        collection_interval: 10s
      k8sobjects:
        objects:
          - exclude_watch_type:
              - DELETED
            group: events.k8s.io
            mode: watch
            name: events
      prometheus:
        config:
          scrape_configs:
            - job_name: opentelemetry-collector
              scrape_interval: 10s
              static_configs:
                - targets:
                    - ${env:MY_POD_IP}:8888

    exporters:
      otlphttp/victoriametrics:
        endpoint: http://vmsingle-metrics.monitoring.svc.cluster.local:8428/opentelemetry

      otlphttp/victorialogs:
        endpoint: http://vlsingle-logs.monitoring:9428/insert/opentelemetry

      # otlphttp/victoriatraces:
      #   endpoint: http://vtsingle-traces.monitoring:9428/insert/opentelemetry

    processors:
      batch: {}
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25

    service:
      extensions:
        - health_check
      pipelines:
        metrics:
          receivers:
            - otlp
            - prometheus
            - k8s_cluster
          processors:
            - memory_limiter
            - batch
          exporters:
            - otlphttp/victoriametrics
        logs:
          receivers:
            - otlp
            - k8sobjects
          processors:
            - memory_limiter
            - batch
          exporters:
            - otlphttp/victorialogs
            # traces:
            #   receivers:
            #     - otlp
            #   processors:
            #     - memory_limiter
            #     - batch
            #   exporters:
            #     - otlphttp/victoriatraces
      telemetry:
        metrics:
          readers:
            - pull:
                exporter:
                  prometheus:
                    host: ${env:MY_POD_IP}
                    port: 8888
