---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-agent
  namespace: monitoring
spec:
  mode: daemonset
  targetAllocator:
    prometheusCR:
      enabled: true
      podMonitorSelector: {}
      serviceMonitorSelector: {}
  config:
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    exporters:
      otlp:
        endpoint: open-telemetry-gateway-collector.monitoring.svc.cluster.local:4317
        tls:
          insecure: true

    processors:
      batch:

    service:
      pipelines:
        metrics:
          receivers:
            - otlp
          processors:
            - batch
          exporters:
            - otlp
