---
# yaml-language-server: $schema=https://kubernetes-schemas.jacob-williams.me/opentelemetry.io/opentelemetrycollector_v1beta1.json
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry-prometheus
spec:
  mode: statefulset
  targetAllocator:
    enabled: true
    serviceAccount: opentelemetry-prometheus-collector
    prometheusCR:
      enabled: true
      podMonitorSelector: {}
      serviceMonitorSelector: {}
  config:
    receivers:
      prometheus:
        trim_metric_suffixes: true
        config:
          scrape_configs:
            - job_name: 'otel-collector'
              scrape_interval: 10s
              static_configs:
                - targets:
                    - '0.0.0.0:8888'
              relabel_configs:
                # Drop any target whose job or namespace matches a pattern
                - source_labels:
                    - __meta_kubernetes_pod_label_app
                  regex: "dragonfly"
                  action: drop

    exporters:
      debug: {}

    service:
      pipelines:
        metrics:
          receivers:
            - prometheus
          exporters:
            - debug
