---
# yaml-language-server: $schema=https://kubernetes-schemas.jacob-williams.me/opentelemetry.io/opentelemetrycollector_v1beta1.json
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry-prometheus
spec:
  mode: statefulset
  targetAllocator:
    enabled: true
    serviceAccount: opentelemetry-prometheus-collector
    prometheusCR:
      enabled: true
      podMonitorSelector: {}
      serviceMonitorSelector: {}
  config:
    receivers:
      prometheus: {}

    exporters:
      debug: {}

    service:
      pipelines:
        metrics:
          receivers:
            - prometheus
          exporters:
            - debug
