---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app pgadmin
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-labs
        namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      pgadmin:
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: docker.io/dpage/pgadmin4
              tag: 9.9@sha256:5d9624a93634d1c5e595619cc57b1d330758120d1baf445fa97300c0c1fc3c0a
            env:
              PGADMIN_CONFIG_X_CONTENT_TYPE_OPTIONS: "''"
              PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
              PGADMIN_CONFIG_X_XSS_PROTECTION: 0
            envFrom:
              - secretRef:
                  name: pgadmin-secret
            resources:
              requests:
                memory: 256Mi
              limits:
                memory: 256Mi
        pod:
          securityContext:
            runAsUser: 0
            runAsGroup: 0
    service:
      app:
        controller: pgadmin
        ports:
          http:
            port: &port 80
    route:
      app:
        hostnames:
          - "pgadmin.${SECRET_DOMAIN}"
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
    persistence:
      config:
        existingClaim: pgadmin
        globalMounts:
          - path: /var/lib/pgadmin
      server-json:
        enabled: true
        type: configMap
        name: pgadmin-configmap
        globalMounts:
          - path: /pgadmin4/servers.json
            subPath: servers.json
