---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app pgadmin
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-labs
        namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      pgadmin:
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          fix-ownership:
            image:
              repository: docker.io/library/busybox
              tag: 1.37.0@sha256:db142d433cdde11f10ae479dbf92f3b13d693fd1c4a94c56d8b14fe4b7c17dec
            command:
              - "sh"
              - "-c"
              - "chown -R 5050:5050 /var/lib/pgadmin"
            securityContext:
              runAsUser: 0
              runAsNonRoot: false
        containers:
          main:
            image:
              repository: docker.io/dpage/pgadmin4
              tag: 9.8@sha256:d115bcd737940a6cfb61a54439d50de8b850e0782e2363102c9fa761f4022f49
            env:
              PGADMIN_UID: "5050"
              PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False" # required behind Envoy reverse proxy
            envFrom:
              - secretRef:
                  name: pgadmin-secret
            resources:
              requests:
                memory: 256Mi
              limits:
                memory: 256Mi
        pod:
          securityContext:
            runAsUser: 5050
            runAsGroup: 5050
            runAsNonRoot: true
            fsGroup: 5050
    service:
      app:
        controller: pgadmin
        ports:
          http:
            port: &port 80
    route:
      app:
        hostnames:
          - "pgadmin.${SECRET_DOMAIN}"
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
    persistence:
      config:
        existingClaim: pgadmin
        globalMounts:
          - path: /var/lib/pgadmin
      server-json:
        enabled: true
        type: configMap
        name: pgadmin-configmap
        globalMounts:
          - path: /pgadmin4/servers.json
            subPath: servers.json
