---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./externalsecret.yaml
components:
  - ../../../../components/volsync
  - ../../../../components/keda/nas-nfs-scaler
configMapGenerator:
  - name: pgadmin-configmap
    files:
      - ./config/servers.yaml
generatorOptions:
  disableNameSuffixHash: true
