---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-telemetry
spec:
  interval: 30m
  chart:
    spec:
      chart: open-telemetry
      version: 0.136.0
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
  values:
    manager:
      collectorImage:
        repository: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s

