---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-postgres-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: vector-postgres
        group: infrastructure
        url: tcp://postgres16-vector-rw.database.svc.cluster.local:5432
        interval: 1m
        ui:
          hide-url: true
          hide-hostname: true
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: pushover
