---
apiVersion: v1
kind: Service
metadata:
  name: postgres-vector-lb
  annotations:
    external-dns.alpha.kubernetes.io/hostname: postgres-vector.jacob-williams.me
    io.cilium/lb-ipam-ips: 10.0.40.51
spec:
  type: LoadBalancer
  ports:
    - name: postgres-vector
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres16-vector
    role: primary
