# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:OUHNXVxKgTjC63mtzimWP+63Jrs4xbCy9RdYbtcWjHU=,iv:9+LIMv4RGSbiNE0liiNMxNfnWRD7qdgIMapK7N1POvg=,tag:/PzCZ88RV8lK+mhO0Vo5og==,type:str]
sops:
  age:
    - recipient: age1nv98v759d8wcplj6rjetmdh5h8t2jl8vawvlvc3lychjfazl6d7qcd2zxa
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTmppVWJ4RGM3MEtxeXNJ
        b3FWM0dNdGpxaU8yRHM3K1hBKzZmTjlVdGhZCms5S3NsU0NaMWZpSzhJMVJKN3Ew
        RnNQK0YvbDRUQzBlV3RDYXZyV0xjSFUKLS0tIEJkSzF3NE5ka1BKZkNPSWdtMkZI
        N1ZjNW53d201dkVLamcxdFk3bWExbFkKLczcraz3WEA9T1TlQGGb5JimBpo7UKFY
        1hfi/l8qAag+eMFIsD3ipIkbvRP/Qqp+vbyatKYR0c22oAkbWC/YbA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-01T16:57:23Z"
  mac: ENC[AES256_GCM,data:2U6xDtohl5J7Dg9eqh+QwJJ2Z0FJpPoD5CG+Fm7eLJPhDopZeI7ukAhgig2eXTqWIGIBBgYOj63RSCm6GOMViZJQGzZhDkbgp52G7WfdN0UII+ThUjjlkdkSm5RueiFHS0B/YvvJizc9G+ofVKkuGnfmxHVG4wNCw+rDxuevP3Q=,iv:37kLXTo2YPrdKrryu+W0jk+nZNfgu8d29VSU5qOipd8=,tag:jBsqWMD5QDMCZw3Nd51Fxw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
