# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:IpzJvjUkB5rcAI3rc3apr+gRLMsXOmPX0UmKgrTWeUg=,iv:Ep7vD4ZHPGB374FW8balGROi8T+aIrIUzf+3JcgiydU=,tag:rjJ/7wfbLeBbSdlW4n1jMw==,type:str]
sops:
  age:
    - recipient: age1487fv3g48lmeznwxktqgvyzaj63hxxhts5mm4zlxvkhm82gcnfpsh2rkqa
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyT0JZczZPd0FReWdvYUJU
        ZFRVU016ZldPa2hldDFVWWtyWnZnKzgvQTFNClM2ZmV2YURRR3ZFUm9EMGcxdUhx
        bFZ5bWQzeGozSUJpYVNHRzdoR1JyaWsKLS0tIExSRW45YW4vb2RpUzZJNlRQeXFD
        NU8wZy9ROWxUaXJ4eVR5SjJucVF6a3MKFHQrMIQWwTkIipe02zdZAdFFOjVKV2fP
        Go7FkSiuYj+6RgSkoxqbxmBKkCdhwgzhntmK7U7WSrKYtwCglzgykw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-01T23:27:27Z"
  mac: ENC[AES256_GCM,data:+Uju7mKXRR3DIf/r22o3SRf0ttPa3rM6mK60Ubs4p2Gutb2FxiuD7FR3FQEsnBGHAJDSOI2tCVrPg7bS8FXusMImVsxnD8iTxfLCbKQSeC/gFMaJh00aLzMjV5X9m5aoTcURYJ8recuUOk54OImEybsgnLnW0vaNHoZIBy8mU0U=,iv:amryLjX85i7Z7NxVava/Qu591qpNhatwMLElfeXkuCs=,tag:DZwTEn4zG+wqisIUsVt6wA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
