---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: keycloak-secret
    creationPolicy: Owner
    template:
      data:
        # Postgres init vars
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_DBNAME: keycloak
        INIT_POSTGRES_USER: "{{ .DB_USER }}"
        INIT_POSTGRES_PASS: "{{ .DB_PASSWORD }}"
        # Keycloak Config
        KC_DB: postgres
        KC_DB_PASSWORD: "{{ .DB_PASSWORD }}"
        KC_DB_USERNAME: "{{ .DB_USER }}"
        KC_DB_URL: jdbc:postgresql://postgres16-rw.database.svc.local/keycloak
        KC_HEALTH_ENABLED: "true"
        KC_METRICS_ENABLED: "true"
        KC_BOOTSTRAP_ADMIN_USERNAME: "{{ .BOOTSTRAP_USER }}"
        KC_BOOTSTRAP_ADMIN_PASSWORD: "{{ .BOOTSTRAP_PASSWORD }}"
  dataFrom:
    - extract:
        key: keycloak
---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret keycloak-initdb
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *secret
    template:
      data:
        INIT_POSTGRES_SUPER_USER: '{{ .POSTGRES_SUPER_USER }}'
        INIT_POSTGRES_SUPER_PASS: '{{ .POSTGRES_SUPER_PASS }}'
  dataFrom:
    - extract:
        key: cloudnative-pg
