---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: codecentric
  driftDetection:
    mode: enabled
    ignore:
      - paths:
          - /spec/replicas
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    image:
      tag: "26.6.1"
    extraInitContianers:
      init-db:
        image:
          repository: ghcr.io/home-operations/postgres-init
          tag: 17
        envFrom:
          - secretRef:
              name: keycloak-secret
          - secretRef:
              name: keycloak-initdb
    httpRoute:
      enabled: true
      hostnames:
        - "sso.${SECRET_DOMAIN}"
      parentRefs:
        - name: internal
          namespace: network
          sectionName: https
    dbchecker:
      enabled: true
    database:
      vendor: postgres
      hostname: postgres16-rw.database.svc.cluster.local
      port: 5432
      database: forgejo
      username: forgejo
      existingSecret: keycloak-secret
      existingSecretKey: KC_DB_PASSWORD
