---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: immich-secret
    template:
      engineVersion: v2
      data:
        REDIS_PASSWORD: "{{ .DRAGONFLY_PASSWORD }}"
        DB_USERNAME: "{{ .IMMICH_DB_USER }}"
        DB_PASSWORD: "{{ .IMMICH_DB_PASSWORD }}"
  dataFrom:
    - extract:
        key: immich
    - extract:
        key: dragonfly
