---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actions-runner-controller
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: actions-runner-controller-secret
    template:
      data:
        github_app_id: '{{ .app_id }}'
        github_app_installation_id: '{{ .app_installation_id }}'
        github_app_private_key: '{{ .app_private_key }}'
  dataFrom:
    - extract:
        key: github
