---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: immich-secret
    template:
      engineVersion: v2
      data:
        # REDIS_PASSWORD: "{{ .DRAGONFLY_PASSWORD }}"
        DB_USERNAME: "{{ .IMMICH_DB_USER }}"
        DB_PASSWORD: "{{ .IMMICH_DB_PASSWORD }}"
  dataFrom:
    - extract:
        key: immich
    - extract:
        key: dragonfly
