# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: authentik-secret
    template:
      data:
        # Authentik DBs
        AUTHENTIK_POSTGRESQL__HOST: &dbhost postgres16-rw.database.svc.cluster.local
        AUTHENTIK_POSTGRESQL__NAME: &dbname authentik
        AUTHENTIK_POSTGRESQL__USER: &dbuser '{{ .AUTHENTIK_POSTGRES_USER }}'
        AUTHENTIK_POSTGRESQL__PASSWORD: &dbpass '{{ .AUTHENTIK_POSTGRES_PASS }}'
        AUTHENTIK_REDIS__DB: '1'
        # Authentik bootstrap
        AUTHENTIK_BOOTSTRAP_EMAIL: '{{ .AUTHENTIK_BOOTSTRAP_EMAIL }}'
        AUTHENTIK_BOOTSTRAP_PASSWORD: '{{ .AUTHENTIK_BOOTSTRAP_PASSWORD }}'
        AUTHENTIK_BOOTSTRAP_TOKEN: '{{ .AUTHENTIK_TOKEN }}'
        AUTHENTIK_SECRET_KEY: '{{ .AUTHENTIK_SECRET_KEY }}'
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        EMAIL_SERVER: '{{ .EMAIL_SERVER }}'
        EMAIL_USER: '{{ .AUTHENTIK_MG_USERNAME }}'
        EMAIL_FROM: 'Authentik <{{ .EMAIL_FROM }}>'
        EMAIL_PASS: '{{ .AUTHENTIK_MG_PASSWORD }}'
  dataFrom:
    - extract:
        key: authentik
    - extract:
        key: mailgun
    - extract:
        key: cloudnative-pg
---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret authentik-initdb
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *secret
    template:
      data:
        INIT_POSTGRES_SUPER_USER: '{{ .POSTGRES_SUPER_USER }}'
        INIT_POSTGRES_SUPER_PASS: '{{ .POSTGRES_SUPER_PASS }}'
  dataFrom:
    - extract:
        key: cloudnative-pg
