---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authentik-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AUTHENTIK_SECRET_KEY: "{{ .authentik_secret_key }}"
        AUTHENTIK_EMAIL__HOST: "{{ .authentik_email_host }}"
        AUTHENTIK_EMAIL__USERNAME: "{{ .authentik_email_username }}"
        AUTHENTIK_EMAIL__PASSWORD: "{{ .mailgun_authentik_smtp_password }}"
        AUTHENTIK_EMAIL__FROM: "{{ .authentik_email_from }}"
        # AUTHENTIK_REDIS__PASSWORD: "{{ .DRAGONFLY_PASSWORD }}"
  dataFrom:
    - extract:
        key: authentik
    - extract:
        key: mailgun
    - extract:
        key: dragonfly
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-db
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authentik-db-secret
    template:
      type: Opaque
      data:
        AUTHENTIK_POSTGRESQL__NAME: "authentik"
        AUTHENTIK_POSTGRESQL__HOST: 'postgres16-vector-rw.database.svc.cluster.local'
        AUTHENTIK_POSTGRESQL__USER: "{{ .authentik_postgres_user }}"
        AUTHENTIK_POSTGRESQL__PASSWORD: "{{ .authentik_postgres_password }}"
        AUTHENTIK_POSTGRESQL__SSLMODE: "require"
  dataFrom:
    - extract:
        key: authentik
