---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: 2025.4.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  values:
    global:
      podAnnotations:
        secret.reloader.stakater.com/reload: authentik-secret, authentik-db-secret
      deploymentStrategy:
        type: RollingUpdate
      envFrom:
        - secretRef:
            name: authentik-secret
        - secretRef:
            name: authentik-db-secret

    authentik:
      log_level: info
      redis:
        host: dragonfly.database.svc.cluster.local
        password: ""
        db: 1

    postgresql:
      enabled: false

    prometheus:
      rules:
        enabled: true

    redis:
      enabled: false

    server:
      podAnnotations:
        secret.reloader.stakater.com/reload: auto
      autoscaling:
        enabled: true
        minReplicas: 1
      ingress:
        enabled: true
        ingressClassName: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
        hosts:
          - &host "auth.${SECRET_DOMAIN}"
        paths:
          - /
        tls: [hosts: [*host]]
      metrics:
        prometheus:
          serviceMonitor:
            enabled: true

    worker:
      autoscaling:
        enabled: true
        minReplicas: 1
