---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync-system
  values:
    controllers:
      minecraft:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: itzg/minecraft-server
              tag: 2025.2.1-java21-graalvm@sha256:b21fbe9a01eded5d343c22596f4ddd4054e2e2b6a600b2a48abddc58ec6ab344
            envFrom:
              - secretRef:
                  name: minecraft-secret
            env:
              EULA: "TRUE"
              TYPE: "FABRIC"
              USE_AIKAR_FLAGS: "true"
              DIFFICULTY: "2"
              ENABLE_WHITELIST: "true"
              WHITELIST: |-
                FlexPheonix
                jwilliams21
              EXISTING_WHITELIST_FILE: "SKIP"
              CURSEFORGE_FILES: |-
                https://www.curseforge.com/minecraft/mc-mods/ambientsounds
                https://www.curseforge.com/minecraft/mc-mods/better-stats
                https://www.curseforge.com/minecraft/mc-mods/camera-utils
                https://www.curseforge.com/minecraft/mc-mods/cave-dust
                https://www.curseforge.com/minecraft/mc-mods/cloth-config
                https://www.curseforge.com/minecraft/mc-mods/continuity
                https://www.curseforge.com/minecraft/mc-mods/durability-tooltip
                https://www.curseforge.com/minecraft/mc-mods/falling-leaves-fabric
                https://www.curseforge.com/minecraft/mc-mods/forge-config-api-port-fabric
                https://www.curseforge.com/minecraft/mc-mods/geophilic
                https://www.curseforge.com/minecraft/mc-mods/irisshaders
                https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks
                https://www.curseforge.com/minecraft/mc-mods/noisium
                https://www.curseforge.com/minecraft/mc-mods/pick-up-notifier
                https://www.curseforge.com/minecraft/mc-mods/puzzles-lib
                https://www.curseforge.com/minecraft/mc-mods/sodium
                https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib
                https://www.curseforge.com/minecraft/mc-mods/tcdcommons
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: minecraft
        ports:
          http:
            port: 8123
    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        className: external
        hosts:
          - host: "minecraft.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        existingClaim: minecraft
        globalMounts:
          - path: /data
