---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: outline
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: outline-secret
    creationPolicy: Owner
    template:
      data:
        INIT_POSTGRES_DBNAME: outline
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .db_username }}"
        INIT_POSTGRES_PASS: "{{ .db_password }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

        DATABASE_URL: "postgres://{{ .db_username }}:{{ .db_password }}@postgres16-rw.database.svc.cluster.local/outline"
        DATABASE_SCHEMA: "outline"
        REDIS_URL: "redis://dragonfly.database.svc.cluster.local:6379"
        SECRET_KEY: "{{ .secret_key }}"
        UTILS_SECRET: "{{ .utils_secret }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: outline
