---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app outline
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-labs
        namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      outline:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: RollingUpdate
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 17
            envFrom: &envFrom
              - secretRef:
                  name: outline-secret
        containers:
          app:
            image:
              repository: docker.getoutline.com/outlinewiki/outline
              tag: 0.87.4@sha256:659a8bf588ef2d914ef4e519409f38e472145369383c0a5aa89b286b4dfe860c
            envFrom:
              - configMapRef:
                  name: outline-secret
            # probes:
            #   liveness: &probes
            #     enabled: true
            #     custom: true
            #     spec:
            #       httpGet:
            #         path: /server/ping
            #         port: 2283
            #       initialDelaySeconds: 0
            #       periodSeconds: 10
            #       timeoutSeconds: 1
            #       failureThreshold: 5
            #   readiness: *probes
            #   startup:
            #     enabled: false
            resources:
              requests:
                cpu: 10m
                memory: 512Mi
                # limits:
                #   memory: 500Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
        pod:
          enableServiceLinks: false
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: outline
        ports:
          http:
            port: 3000
    route:
      main:
        enabled: true
        hostnames:
          - "outline.${SECRET_DOMAIN}"
        parentRefs:
          # - name: external
          #   namespace: network
          #   sectionName: https
          - name: internal
            namespace: network
            sectionName: https

    persistence:
      data:
        existingClaim: outline
        globalMounts:
          - path: /var/lib/outline/data
