apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:DoEDYRkqYh3hYRn3Ur0CbFO6HT4ib5fNQO+j48/DUhmH3YPA5zbY2g==,iv:jx6aiPobRYa5OuzFRdPV/SYOcCpIRLGfc/f7gZvGF6s=,tag:LgWTrstUg6n+tLOY+0OYyA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f55sgl9ayk3mfecrajq4elq29y4ktekge7mr8vczfn9xyu37pa5qwptwu0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBybGxqbVVOQVNSdGhmVDZi
            dzVtQzFqdHVrU0R1WCtqWDZaQVd5VGdjVFJVClYvV2NnN1MrU3FPdHI2QklKdFVy
            bDd2Rk5lNE9pZ3dkY3hZQ2xCUms1YnMKLS0tIEhRWkhoOUx6RDk1TGh0NDVaLzFP
            TUV6OWhESGw0UVloZFdOQjhWcHFJeVUKMni6023B10MkAc8VqzjvNuwgHdhyhdNN
            m52rrCs7WGogz49tkHEN4PjexuPOvDSk5BP0Y40VdY8PM3yeaEcn1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-16T23:54:53Z"
    mac: ENC[AES256_GCM,data:hyIT/O5rOVN7hYYORycryJQjgB1EFEUtsJLbXozKnquEJTldfOoBqx5iH6rF6LtOGiUHkPvYt+4R43Vw5H7uJU3sZfgx7UVMv96UqEk612RAKK90+uulsWiRG8+niqe26RFmgS5s6xb9q4pHJRXImFj1RmbBBe18vFr5kXWz29g=,iv:USovQSKl1yB2m7MGJBTRJKJG5IJIR9zDIFVUKmMxsI4=,tag:wVS/XRXl9eKO1yx1y4rXyQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
