---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: forgejo-secret
    creationPolicy: Owner
    template:
      data:
        # Postgres init vars
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_DBNAME: forgejo
        INIT_POSTGRES_USER: "{{ .DB_USER }}"
        INIT_POSTGRES_PASS: "{{ .DB_PASSWORD }}"

        # Forgejo Config
        FORGEJO__server__ROOT_URL: "https://forgejo.${SECRET_DOMAIN}"
        FORGEJO__database__DB_TYPE: postgres
        FORGEJO__database__HOST: postgres16-rw.database.svc.cluster.local:5432
        FORGEJO__database__NAME: forgejo
        FORGEJO__database__USER: "{{ .DB_USER }}"
        FORGEJO__database__PASSWD: "{{ .DB_PASSWORD }}"
        FORGEJO__mailer__ENABLED: "true"
        FORGEJO__mailer__PROTOCOL: "smtps"
        FORGEJO__mailer__USER: "{{ .MG_USERNAME }}"
        FORGEJO__mailer__PASSWD: "{{ .MG_PASSWORD }}"
        FORGEJO__mailer__SMTP_ADDR: "{{ .EMAIL_SERVER }}"
        FORGEJO__mailer__SMTP_PORT: "465"

  dataFrom:
    - extract:
        key: forgejo
    - extract:
        key: mailgun
---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret forgejo-initdb
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *secret
    template:
      data:
        INIT_POSTGRES_SUPER_USER: '{{ .POSTGRES_SUPER_USER }}'
        INIT_POSTGRES_SUPER_PASS: '{{ .POSTGRES_SUPER_PASS }}'
  dataFrom:
    - extract:
        key: cloudnative-pg
