---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app immich-test
  namespace: flux-system
spec:
  targetNamespace: default
  dependsOn:
    - name: cloudnative-pg-vector-cluster
    - name: dragonfly-cluster
    - name: external-secrets-stores
  path: ./kubernetes/apps/default/immich-test/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: immich
