---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unifi
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: unifi-db
      namespace: default
    - name: volsync
      namespace: volsync-system
  values:
    controllers:
      unifi:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/goofball222/unifi
              tag: 8.6@sha256:4b13f23ba293b6cb9c89931a9959b2cdec0443ac0dc53195a886ae5468ca8b39
            env:
              - name: DB_MONGO_LOCAL
                value: "false"
              - name: MONGO_PASS
                valueFrom:
                  secretKeyRef:
                    name: unifi
                    key: mongopass
              - name: MONGO_USER
                value: unifi
              - name: UNIFI_DB_NAME
                value: unifi
              - name: TZ
                value: America/Chicago
              - name: PGID
                value: "65534"
              - name: PUID
                value: "65534"
              - name: RUN_CHOWN
                value: "false"
              - name: DB_MONGO_URI
                value: "mongodb://$(MONGO_USER):$(MONGO_PASS)@unifi-db-0.unifi-db-svc:27017,unifi-db-1.unifi-db-svc:27017,unifi-db-2.unifi-db-svc:27017/unifi?replicaSet=unifi-db&ssl=false"
              - name: STATDB_MONGO_URI
                value: "mongodb://$(MONGO_USER):$(MONGO_PASS)@unifi-db-0.unifi-db-svc:27017,unifi-db-1.unifi-db-svc:27017,unifi-db-2.unifi-db-svc:27017/unifi_stat?replicaSet=unifi-db&ssl=false"
        ports:
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
                memory: 475Mi
              limits:
                cpu: 200m
                memory: 1Gi
          code-server:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.95.3@sha256:6d74583d68179cbb6ddadc2518b450d2ac3eaec2d342474fe1941e03371cd2cf
            args: [
              "--auth", "none",
              "--user-data-dir", "/config/.vscode",
              "--extensions-dir", "/config/.vscode",
              "--port", "12321",
              "/config"
            ]
            resources:
              requests:
                cpu: 100m
                memory: 360Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: home-assistant
        ports:
          http:
            port: 8123
          code-server:
            port: 12321
    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: external.jacob-williams.me
        className: external
        hosts:
          - host: hass.jacob-williams.me
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
      code-server:
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.jacob-williams.me
        className: internal
        hosts:
          - host: hass-code.jacob-williams.me
            paths:
              - path: /
                service:
                  identifier: app
                  port: code-server
    persistence:
      config:
        existingClaim: home-assistant
        globalMounts:
          - path: /config
      logs:
        type: emptyDir
        globalMounts:
          - path: /config/logs
      tts:
        type: emptyDir
        globalMounts:
          - path: /config/tts
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
