---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: donetick
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: donetick-secret
    creationPolicy: Owner
    template:
      data:
        selfhosted.yaml: |
          # This file is configuration for Donetick
  dataFrom:
    - extract:
        key: donetick
