---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: donetick
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: donetick-secret
    creationPolicy: Owner
    template:
      data:
        INIT_POSTGRES_DBNAME: donetick
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .db_username }}"
        INIT_POSTGRES_PASS: "{{ .db_password }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        selfhosted.yaml: |
          name: "selfhosted"
          is_done_tick_dot_com: false
          is_user_creation_disabled: true
          telegram:
            token: ""
          pushover:
            token: "{{ .pushover_token }}"
          database:
            type: postgres
            host: postgres16-rw.database.svc.cluster.local
            port: 5432
            user: "{{ .db_username }}"
            password: "{{ .db_password }}"
            name: donetick
            migration: true
          jwt:
            secret: {{ .jwt_secret }}
            session_time: 168h
            max_refresh: 168h
          server:
            port: 2021
            read_timeout: 10s
            write_timeout: 10s
            rate_period: 60s
            rate_limit: 300
            cors_allow_origins:
              - "http://localhost:5173"
              - "http://localhost:7926"
              # the below are required for the android app to work
              - "https://localhost"
              - "capacitor://localhost"
            serve_frontend: true
          logging:
            level: "info"
            encoding: "json"
            development: false
          scheduler_jobs:
            due_job: 30m
            overdue_job: 3h
            pre_due_job: 3h
          email:
            host:
            port:
            key:
            email:
            appHost:
          oauth2:
            client_id:
            client_secret:
            auth_url:
            token_url:
            user_info_url:
            redirect_url:
            name:
          # Real-time configuration
          realtime:
            enabled: true
            sse_enabled: true
            heartbeat_interval: 60s
            connection_timeout: 120s
            max_connections: 1000
            max_connections_per_user: 5
            event_queue_size: 2048
            cleanup_interval: 2m
            stale_threshold: 5m
            enable_compression: true
            enable_stats: true
            allowed_origins:
              - "*"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: donetick
