---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-postgres-owner
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: immich-postgres-owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: immich
        property: IMMICH_DB_USER
    - secretKey: password
      remoteRef:
        key: immich
        property: IMMICH_DB_PASSWORD
