---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cluster.yaml
  - ./externalsecret.yaml
  - ./s3-region-secret.yaml
  - ./scheduledbackup.yaml
  - ./superuser-externalsecret.yaml
