---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - ./keycloak/ks.yaml
  - ./ciliumnetworkpolicy.yaml
components:
  - ../../components/common
  - ../../components/netpol-default-deny
