---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodump
spec:
  schedule: '@daily'
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: mongodump
            persistentVolumeClaim:
              claimName: mongodump
          restartPolicy: Never
          containers:
            - name: mongodb
              image: mongo
              command : ["/bin/sh", "-c"]
              args: ["mongodump --uri \"mongodb://unifi-db-0.unifi-db-svc:27017,unifi-db-1.unifi-db-svc:27017,unifi-db-2.unifi-db-svc:27017/?replicaSet=rs0\" -u $(MONGODB_USERNAME) -p $(MONGODB_PASSWORD) --authenticationDatabase admin -o /usr/share/mongodump/$(date +\"%d%m%H\")"]
              env:
              - name: MONGODB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: unifi-db-unifi-unifi
                    key: password
              - name: MONGODB_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: unifi-db-unifi-unifi
                    key: username
              volumeMounts:
              - mountPath: "/usr/share/mongodump/"
                name: unifi-db-backup
