---
devices:
  - name: zwave
    groups:
      - count: 1000
        usb:
          - vendor: 10c4
            product: ea60
  - name: coral
    groups:
      - count: 1000
        pci:
          - vendor: 10c4
            device: ea60
