---
# yaml-language-server: $schema=https://kubernetes-schemas.jacob-williams.me/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: stoat
  namespace: self-hosted
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: stoat
  targetNamespace: self-hosted
  dependsOn:
    - name: onepassword-store
      namespace: external-secrets
    - name: mongodb-operator
      namespace: database
    - name: rabbitmq-cluster-operator
      namespace: database
    - name: dragonfly
      namespace: database
    - name: rook-ceph-cluster
      namespace: rook-ceph
  path: ./kubernetes/apps/self-hosted/stoat/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: stoat
