---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name adguardhome-external-dns
spec:
  interval: 1h
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: adguardhome-external-dns
  install:
    crds: Skip
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    crds: Skip
    remediation:
      retries: 5
  values:
    fullnameOverride: *name
    provider:
      name: webhook
    extraArgs:
      webhook-provider-url: http://localhost:8888
    sidecars:
      - name: adguard-webhook
        image: ghcr.io/muhlba91/external-dns-provider-adguard:v8.0.1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8888
            name: http
          - containerPort: 8080
            name: healthz
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /healthz
            port: healthz
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 60
        env:
          - name: LOG_LEVEL
            value: info
          - name: ADGUARD_URL
            value: "http://10.0.0.1:3000"
            valueFrom:
            secretKeyRef:
              name: &secret adguardhome-external-dns-secret
              key: ADGUARD_USER
          - name: ADGUARD_PASSWORD
            valueFrom:
              secretKeyRef:
                name: *secret
                key: ADGUARD_PASSWORD
          - name: SERVER_HOST
            value: "0.0.0.0"
          - name: HEALTHZ_HOST
            value: "0.0.0.0"
          - name: DRY_RUN
            value: "false"
        resources:
          requests:
            cpu: 3m
            memory: 100Mi
          limits:
            memory: 100Mi
    triggerLoopOnEvent: true
    policy: sync
    sources:
      - gateway-httproute
      - gateway-tlsroute
      - service
    txtOwnerId: main
    txtPrefix: k8s.main.
    domainFilters:
      - ${SECRET_DOMAIN}
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
