---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name adguardhome-external-dns
spec:
  interval: 1h
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: adguardhome-external-dns
  install:
    crds: Skip
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    crds: Skip
    remediation:
      retries: 5
  values:
    fullnameOverride: *name
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/muhlba91/external-dns-provider-adguard
          tag: v8.0.1@sha256:267761a55dde38b7cba7b3bff59d0437402538a29659b03144dc9c132c887444
        env:
          - name: ADGUARD_URL
            value: http://10.0.40.1:3000
          - name: ADGUARD_USER
            valueFrom:
              secretKeyRef:
                name: &secret adguardhome-external-dns-secret
                key: ADGUARD_USER
          - name: ADGUARD_PASSWORD
            valueFrom:
              secretKeyRef:
                name: *secret
                key: ADGUARD_PASSWORD
          - name: LOG_LEVEL
            value: debug
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
        service:
          port: 8888
    triggerLoopOnEvent: true
    policy: sync
    sources:
      - gateway-httproute
      - gateway-tlsroute
      - service
    txtOwnerId: main
    txtPrefix: k8s.main.
    domainFilters:
      - ${SECRET_DOMAIN}
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
