---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bjw-s-labs.yaml
  - ./ceph-csi-operator.yaml
  - ./external-dns.yaml
  - ./ingress-nginx.yaml
  - ./mongodb.yaml
  - ./descheduler.yaml
  - ./openebs.yaml
  - ./harbor.yaml
