apiVersion: v1
data:
    token: ENC[AES256_GCM,data:+4Y3a1z5QOANkTZ0rKEC5OiI2ev9I9Z3+BwTvUVaKoOOefieA+0na2yjP6eDoTLkC84j1k6AsSdE4uZJ4yy/L0YjtDtE3wPWjZq+F8s4VKzt+fj4yS/68eIHt0m/yuIBWkS6cv79yedlJIWFnK9+52NU7CGm2jIKf1O5+yEX0g50z1rKtyo+oyTdyZGaPEDcB9dTXQOn3mhXfBJQI9Vv7v4lIg6RHfwDu+wDSrVyZV5cWdus8GyYjUM0q/tUfx4NaMfRqhAUrdaA+eE26yQy8E0a6hiko/Fn/+AY+yNpSOX6XsMcoGub0Z0TP60+d86RnOV5LjsGLjfkh1l3rI95eq1PhrYnxc93UA0+fcI9nyPiRRR0l5uGG1qWMGKPLNT0SFpXbLI5rtamTVBJdx08Wy1eNROT98guQfkLO0b90Vn41UciRXq3/DshhMnxbjF3yH4iYNZI9TVFuD4RW1ny64Q4h4//2OgTL2mAC2W8YABaFviq3hqwy60i5paY6QSc6jSZU/c0jIn6yBhR4Ke4vd647mYSbpqWUgB0T6Up8qQmAdfGLh4ejtTJuH/EqHeS/a3WwuD0CaNjTnf0KXxxgIvpNAy6GKSL9AnvK0lX22A42Yo2pPQwH+/GFe5KFhMebNXBuHHq58JVeEGqETMRwrFVbRnyPKouS84ngVFVwKWCKR4BGSZily5IaBHnZxlXHKwCX6Cv/A5ShZpvYkEs8ablIgOelB5IomeNvR1cCYcKGzS39eiG+Zpew/m1CfsoUZHRxcKU1sOMn4jVbfCZbtV9ztmFasqSiuvirjEvwmdLogmfTq0RTEYk1eketfeEHswfAmjQn4D1GHCiHlHWcT7ynF3JeOEQ2DU/InMLx40y3wWqR+T98LLfwZVWWk8ODuU8umV82UeF+HZJ8OUWpthoBMFB4o39xIo3Ca5tnuinlHKalEzC3BnqbnBOWneGbZQ/grBhba9FoZNTHdq7rf1f26GOgSe969b1Zre66BmgdvlClCryUp6bffFDaPO6EW4VsBz388LObvfdZOQzzHQJ7remfeslwNr+8t6fO6SGdM8ibGlVCTvUPnwuV8nlRfeBUJleIomxCwx/z5c6X3SsCK7EFxfHz+wVnYcAGYne1tuHBFLM232r2+Q=,iv:7MdBPhx6t0L80qMVSh6NAGY+UMyC2U0rE3fSeq9pBeo=,tag:yUtn5KfRy/Bodjym2vna9g==,type:str]
kind: Secret
metadata:
    name: op-token
    namespace: external-secrets
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f55sgl9ayk3mfecrajq4elq29y4ktekge7mr8vczfn9xyu37pa5qwptwu0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdVFraXV3T3dDdUdnSW94
            UVBtZmhJS3owZEJxbmo3SUFFZ2ZHNFQ3UndvCkIvOE9uU0hOU1QySlI5UVgzVytU
            RXBXL0dYVm5pTTZ0elplekx4MU5YRTgKLS0tIE5uSkppYmp0ZnlPN0pEL21PVE5O
            OGkvVml4YzUxVnlXenV6elVOVkZFWHcKLK0kp70iPeIz9wGGuJjiQ9MBuXMVCYCG
            nDlZa0v6o49YWBPwQ8r7CgmUzYTSvTsV7h1tMtNSDUTrGBRCPkNwSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-17T04:40:32Z"
    mac: ENC[AES256_GCM,data:+UFwCFVngwh92m8i38ONsEVDIrp8u9SVv6FN5uD+OSbtUpbbeXYiEj8xbUVsP2jESQUfTCj7l82q7+wgM7IuB/3oh9p09tMBkEhg9ooA9l4t+eanZ9fKU+MlkwbvVHNOOoNntX5XcKC9e3UE/Qfwj6JGZvLTEu2gaGklBbY3xE4=,iv:CYVSJyXnwZy8prM/Qf3JyO4iwJeMo9HNtEABqjvrvco=,tag:yx/FjDd8lk6t6aCTxNdO1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
