---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flagsmith
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: flagsmith-secret
    creationPolicy: Owner
    template:
      data:
        DATABASE_URL: "postgres://{{ .FLAGSMITH_DB_USER }}:{{ .FLAGSMITH_DB_PASSWORD }}@flagsmith-postgres-rw.self-hosted.svc.cluster.local:5432/flagsmith"
        REDIS_URL: "redis://{{ .DRAGONFLY_USER }}:{{ .DRAGONFLY_PASSWORD }}@flagsmith-dragonfly.self-hosted.svc.cluster.local:6379"
        DJANGO_SECRET_KEY: "{{ .SECRET_KEY }}"
        DJANGO_ALLOWED_HOSTS: "flagsmith.${SECRET_DOMAIN},*"
        ENVIRONMENT: production
  dataFrom:
    - extract:
        key: flagsmith
