---
# yaml-language-server: $schema=https://schemas.tholinka.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app envoy-gateway
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  driftDetection:
    mode: enabled
    ignore:
      - paths: [/spec/replicas]
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
      metrics:
        - resource:
            name: cpu
            target:
              averageUtilization: 60
              type: Utilization
          type: Resource
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 300
        scaleDown:
          stabilizationWindowSeconds: 300
