---
apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-configmap
  namespace: default
data:
  PAPERLESS_URL: https://paperless.${SECRET_DOMAIN}
  PAPERLESS_TIME_ZONE: "America/Chicago"
  PAPERLESS_WEBSERVER_WORKERS: "2"
  PAPERLESS_TASK_WORKERS: "2"
  PAPERLESS_CONSUMPTION_DIR: /data/nas/incoming
  PAPERLESS_DATA_DIR: /data/local/data
  PAPERLESS_EXPORT_DIR: /data/nas/export
  PAPERLESS_MEDIA_ROOT: /data/local/media
  PAPERLESS_CONSUMER_POLLING: "60"
  PAPERLESS_CONSUMER_RECURSIVE: "true"
  USERMAP_GID: "65542"
  PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"
  PAPERLESS_TIKA_ENABLED: "1"
  PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
  PAPERLESS_TIKA_ENDPOINT: http://tika:9998
