---
apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-configmap
  namespace: default
data:
  PAPERLESS_TIKA_ENABLED: "1"
  PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
  PAPERLESS_TIKA_ENDPOINT: http://tika:9998
