---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: paperless-secret
    template:
      engineVersion: v2
      data:
        PAPERLESS_SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY }}"
        PAPERLESS_ADMIN_USER: "{{ .PAPERLESS_ADMIN_USER }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .PAPERLESS_ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: paperless
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: paperless-db-secret
    template:
      engineVersion: v2
      data:
        PAPERLESS_REDIS: "redis://{{ .DRAGONFLY_USER }}:{{ .DRAGONFLY_PASSWORD }}@dragonfly.database.svc.cluster.local:6379"
        PAPERLESS_DBHOST: 'postgres16-vector-rw.database.svc.cluster.local'
        INIT_POSTGRES_DBNAME: paperless
        INIT_POSTGRES_HOST: postgres16-vector-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .PAPERLESS_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .PAPERLESS_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: paperless
    - extract:
        key: dragonfly
    - extract:
        key: cloudnative-pg
