---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: paperless-db-secret
    template:
      engineVersion: v2
      data:
        PAPERLESS_REDIS: "redis://{{ .DRAGONFLY_PASSWORD }}@dragonfly.database.svc.cluster.local:6379"
        DB_USERNAME: "{{ .IMMICH_DB_USER }}"
        DB_PASSWORD: "{{ .IMMICH_DB_PASSWORD }}"
  dataFrom:
    - extract:
        key: immich
    - extract:
        key: dragonfly
