---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "unifi-internal-tls"
spec:
  secretName: "unifi-internal-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "jacob-williams.me"
  dnsNames:
    - unifi
    - unifi.self-hosted.svc
    - unifi.self-hosted.svc.cluster.local
    - 127.0.0.1
