---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minecraft
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: minecraft-secret
    template:
      engineVersion: v2
      data:
        CF_API_KEY: "{{ .CURSEFORGE_API_KEY }}"
  dataFrom:
    - extract:
        key: minecraft
