# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minecraft
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      version: 4.26.3
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
  - name: rook-ceph-cluster
    namespace: rook-ceph
  - name: volsync
    namespace: volsync-system
  values:
    # deploymentAnnotations:
    #   secret.reloader.stakater.com/reload: minecraft-survival-secret
    image:
      repository: ghcr.io/itzg/minecraft-server
      tag: stable@sha256:498b3e03fc49cde4370f2f5a20552751526c8d6774dde12d5f4a0b92c95b00b5
    resources:
      requests:
        cpu: 500m
      limits:
        memory: 10Gi
    securityContext:
      runAsUser: 1000
      fsGroup: 100
    livenessProbe:
      enabled: false
      command:
        - echo
      initialDelaySeconds: 30
      periodSeconds: 5
      failureThreshold: 20
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
      enabled: false
      command:
        - echo
      initialDelaySeconds: 30
      periodSeconds: 5
      failureThreshold: 20
      successThreshold: 1
      timeoutSeconds: 1
    startupProbe:
      command:
        - echo
      enabled: false
      failureThreshold: 30
      periodSeconds: 10
    extraEnv:
      TZ: America/Chicago
      ENABLE_AUTOPAUSE: FALSE # Doesn't work in Kubes
      CURSEFORGE_FILES: |
        ambientsounds
        better-stats
        camera-utils
        cave-dust
        cloth-config
        continuity
        creativecore
        durability-tooltip
        fabric-api
        falling-leaves-fabric
        forge-config-api-port-fabric
        geophilic
        irisshaders
        mouse-tweaks
        noisium
        pick-up-notifier
        puzzles-lib
        sodium
        supermartijn642s-config-lib
        tcdcommons
        mc2discord
    persistence:
      dataDir:
        enabled: true
        existingClaim: *app
    serviceAnnotations:
      mc-router.itzg.me/externalServerName: &host minecraft.${SECRET_DOMAIN}
    minecraftServer:
      eula: true
      version: "1.21.4"
      type: FABRIC
      overrideServerProperties: true
      jvmXXOpts: "-XX:MaxRAMPercentage=75"
      memory: 8192M
      difficulty: normal
      spawnProtection: 0
      gameMode: survival
      pvp: true
      onlineMode: true
      whitelist: "FlexPheonix,jwilliam21,l0l00k"
      # ops: "Vrozaksen"
      # motd: "Just Vanilla Survival"
      # worldSaveName: survival
      viewDistance: 16
      # serviceAnnotations:
      #   lbipam.cilium.io/ips: ${SVC_SURVIVAL_ADDR}
      # serviceType: LoadBalancer
      autoCurseForge:
        apiKey:
          key: CF_API_KEY
          existingSecret: minecraft-secret
          secretKey: CF_API_KEY
      rcon:
        enabled: true
        existingSecret: minecraft-secret
        secretKey: RCON_PASSWORD
      extraPorts:
      - name: metrics
        containerPort: 9225
        protocol: TCP
        service:
          enabled: true
          embedded: false
          type: ClusterIP
          port: 9225
        ingress:
          ingressClassName: external
          enabled: true
          annotations:
            external-dns.alpha.kubernetes.io/target: mc.${SECRET_DOMAIN}
            external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          hosts:
           - name: *host
