---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dragonfly
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: dragonfly-secret
    template:
      engineVersion: v2
  data:
    - secretKey: username
      remoteRef:
        key: dragonfly
        property: DRAGONFLY_USER
    - secretKey: password
      remoteRef:
        key: dragonfly
        property: DRAGONFLY_PASSWORD
