apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:TLoRBuTNCDm6FQ8C3tHMs45fvSHlJKKQD7zX0J3mv6Q=,iv:MTctK1Am8eBoKmdSEfcmdI6C8YHP3cITNO7g4+cAgQo=,tag:96FE8KvwlUUFx3nLc1twFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f55sgl9ayk3mfecrajq4elq29y4ktekge7mr8vczfn9xyu37pa5qwptwu0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RFVvcENub09mVDRyMG5i
            UklweEp1OCs0Z2VIWkpqV3lBZTZVSGhHMVM4CmV0S0tFZmRaNm5YdWRGN09wTjJX
            ckgrOHZUYjR1UTdJbHkzWXdiQ1VmczAKLS0tIFROMUhxNVpFUVRuMzVvcC9ORjV2
            QlZlUXZ3YjR4bW1Da2tkS0dKY252Mm8KZz+4rAu6PdUbOnpUAStqDbtZdzJr8XM1
            5qKEGd5S7XuLCKPrpMD1Y/A67cP4JCYoRhp3Hns+4zZ9XLpW75kjCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-17T03:54:56Z"
    mac: ENC[AES256_GCM,data:pNLCAsxQ+Nqw5CR4KvXYyFhqzMm5nbW1b0D+qtjYsKNPFHKIPf2Q+QXeTDB9ocBqIhO+dKDlSOpWqEKBBuHuzyTOqddhW6K3/UIRbQRZN5WszO2X0laxI5QSK6UtS3JJkp0kifpdGWXy0AJu2CdYGQD0UVwcGWMKHL5N826zNUQ=,iv:aG0GRRdoOg8zNBOF7TeXkoMFJQu6GsDRjVE6gNnv87o=,tag:elSveC3bQ1LGgBI1CZE38Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
