apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:9WVpuxrqrHVtOboSQSS30JLTAycI8CsSFm4fXyso3aY=,iv:v94JpaWSUQFKaygAxnqdmOTJkJ8JB51HMLFxukW/FV8=,tag:S65bEjPcpDxMDP/PPqe4Hg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f55sgl9ayk3mfecrajq4elq29y4ktekge7mr8vczfn9xyu37pa5qwptwu0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbnl0dVdyYU9xQ2tVd2M1
            V005eEFQZGMxaS9ONjNCcmNMaGJQYVJNRnlVCjRUK2U0UlphMUZsSmNxandIU0Va
            OVB1a0kvMGs2eFBxdzJZSnhNWS9MVzAKLS0tIGRmS0V4R1FMcENxMzBWL3JNUFVH
            UDhYeXlQcTd4V3k5SUM0Tk9hS2VxK2sKU4O+0UbNuiF1B8LQ/hmYvDU7F6WdFOpI
            AvF264IU/6H6nIeIcrowzEx6/O0F5FdcazwfHN5XMxX4nOSe8dtE1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-17T06:14:32Z"
    mac: ENC[AES256_GCM,data:lPziOl6SBY2gdX9/7em3WE5kH+qPo8KHkRj4uaLDuXX6nhECjtDOr5ZToSNJNsUp4sAe57gYKEAOuk1lCl/0GQ+6rLDesiIOKafVA5+RFe99QIoNBi1zbYVRYCJfDByDFqqdW3mnt19TNf3T/RdSG6IS2p0DakNWgfemFxWWD14=,iv:AmpEbUfE3rEnpvvM6S6WBjpydH1e5sqx8n72vb5afGc=,tag:ySC3MdVNpblo2XdFL/zi4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
