---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb
spec:
  interval: 30m
  chart:
    spec:
      chart: community-operator
      version: 0.12.0
      sourceRef:
        kind: HelmRepository
        name: mongodb
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: openebs
      namespace: openebs-system
  values:
    crds:
      create: true
    operator:
      watchNamespace: "*"
    monitoring:
      podMonitorEnabled: false
      grafanaDashboard:
        create: true
    resources:
      requests:
        cpu: 5m
        memory: 45Mi
