---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zot-config
data:
  config.json: |-
    {
      "storage": {
        "rootDirectory": "/var/lib/registry"
      },
      "http": {
        "address": "0.0.0.0",
        "port": "5000"
      },
      "log": {
        "level": "debug"
      },
      "extensions": {
        "sync": {
          "registries": [
            {
              "urls": [
                "https://ghcr.io"
              ],
              "content": {
                "prefix": "**"
              },
              "onDemand": true,
              "tlsVerify": true,
              "onlySigned": false
            }
          ]
        },
        "search": {
          "enable": true,
          "cve": {
            "updateInterval": "2h"
          }
        },
        "ui": {
          "enable": true
        }
      }
    }
