---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zot-config
data:
  config.json: |-
    {
      "storage": {
        "rootDirectory": "/var/lib/registry"
      },
      "http": {
        "address": "0.0.0.0",
        "port": "5000"
      },
      "log": {
        "level": "debug"
      },
      "extensions": {
        "sync": {
          "registries": [
          {
            "urls": [
              "https://index.docker.io"
            ],
            "content": [
            {
              "destination": "/docker.io",
              "prefix": "**"
            }
            ],
            "onDemand": true,
            "tlsVerify": true
          },
          {
            "urls": [
              "https://registry.gitlab.com"
            ],
            "content": [
            {
              "destination": "/registry.gitlab.com",
              "prefix": "**"
            }
            ],
            "onDemand": true,
            "tlsVerify": true
          },
          {
            "urls": [
              "https://ghcr.io"
            ],
            "content": [
            {
              "destination": "ghcr.io",
              "prefix": "**"
            }
            ],
            "onDemand": true,
            "tlsVerify": true
          },
          {
            "urls": [
              "https://quay.io"
            ],
            "content": [
            {
              "destination": "/quay.io",
              "prefix": "**"
            }
            ],
            "onDemand": true,
            "tlsVerify": true
          },
          {
            "urls": [
              "https://gcr.io"
            ],
            "content": [
            {
              "destination": "/gcr.io",
              "prefix": "**"
            }
            ],
            "onDemand": true,
            "tlsVerify": true
          },
          {
            "urls": [
              "https://registry.k8s.io"
            ],
            "content": [
            {
              "destination": "/registry.k8s.io",
              "prefix": "**"
            }
            ],
            "onDemand": true,
            "tlsVerify": true
          }
        ]
        },
        "search": {
          "enable": true,
          "cve": {
            "updateInterval": "2h"
          }
        },
        "ui": {
          "enable": true
        }
      }
    }
