---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-configmap
  namespace: default
data:
  # URLS
  IMMICH_SERVER_URL: http://immich-server.default.svc.cluster.local:2283
  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning.default.svc.cluster.local:3003
  PUBLIC_IMMICH_SERVER_URL: https://immich.${SECRET_DOMAIN}
  # SETTINGS
  DISABLE_REVERSE_GEOCODING: "true"
  ENABLE_MAPBOX: "false"
  LOG_LEVEL: log
  NODE_ENV: production
  UPLOAD_LOCATION: /usr/src/app/upload
  # REDIS
  REDIS_HOSTNAME: dragonfly.database.svc.cluster.local
  REDIS_DBINDEX: "1"
  REDIS_PORT: "6379"
  #DB
  DB_HOSTNAME: 'postgres16-vector-rw.database.svc.cluster.local'
  DB_PORT: "5432"
  DB_DATABASE_NAME: "immich"
