apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: rook-ceph-dashboard-password
spec:
  deletionPolicy: Delete
  refreshInterval: 10s
  secretStoreRefs:
    - name: onepassword-connect
      kind: ClusterSecretStore
  selector:
    secret:
      name: rook-ceph-dashboard-password
  data:
    - match:
        remoteRef:
          remoteKey: rook-ceph
