apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:CKr/k74M7iD4BiuCFkETp+r5BsDvu4X6REKsq+4wMD7L6JU/RF/uXg==,iv:rqbAy9t/efsr3v1kvPA58wfQiU6VQDItsveSGmFrU6w=,tag:TPhTXnlsVEavl72qXIV26A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f55sgl9ayk3mfecrajq4elq29y4ktekge7mr8vczfn9xyu37pa5qwptwu0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWjFxMHBoWTFMVzZDNWdD
            MkdVMHNiU0NSdFA2YlE5cHpmMWxOdnljNFZNCmhXa0YyUG0yb2syb25KakdVVXpm
            ZTU3UjR3TjQ1RXV0N2hIckZWY2dyM2MKLS0tIEkreHlBNlF4ZzhoaUowbzBUZzE2
            aXVOdDM2OFcyVWF1ZENiZjdNdTNKdUkK1asA2vILa/h7r5rNZdxm1NbIVYySqo9v
            1U6uoN2vM2mPTzLzowejEb8U/PTbGW4Ja2o6TQx/NLA0C04BNlzaJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-17T00:45:47Z"
    mac: ENC[AES256_GCM,data:r9RT7KDXh837tksC3BQ6pCYaLIr04KdgCCXqlvwpGynsixITKvrhbIEWNquzvm+Fa8/cmDUD7pK57RuWZJWt1crcguAQ68Tjtj+qhWL9nfK1b45/3sPk+FY0BBqx0ffslKInmXMa8J9lSW0SqoDioi9kSkyeZU7mu1AZdFTSlt4=,iv:qZJzhiq15JNuO1vyz8JGI864broSLw9txTSmLdfSV9g=,tag:LxuWOYlDHYXodnTG6tFU/A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
