# https://github.com/VictoriaMetrics/helm-charts/issues/2420
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app victoria-crds
  namespace: &namespace monitoring
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/monitoring/victoria/crds
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 5m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app victoria-operator
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
    - name: victoria-crds
  path: ./kubernetes/apps/monitoring/victoria/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  # ---
  # # yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
  # apiVersion: kustomize.toolkit.fluxcd.io/v1
  # kind: Kustomization
  # metadata:
  #   name: &app victoria-metrics
  # spec:
  #   commonMetadata:
  #     labels:
  #       app.kubernetes.io/name: *app
  #   dependsOn:
  #     - name: victoria-operator
  #   path: ./kubernetes/apps/monitoring/victoria/metrics
  #   prune: true
  #   sourceRef:
  #     kind: GitRepository
  #     name: flux-system
  #     namespace: flux-system
  #   interval: 1h
  #   retryInterval: 2m
  #   timeout: 5m
  # ---
  # # yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
  # apiVersion: kustomize.toolkit.fluxcd.io/v1
  # kind: Kustomization
  # metadata:
  #   name: &app victoria-logs
  # spec:
  #   commonMetadata:
  #     labels:
  #       app.kubernetes.io/name: *app
  #   dependsOn:
  #     - name: victoria-operator
  #   path: ./kubernetes/apps/monitoring/victoria/logs
  #   prune: true
  #   sourceRef:
  #     kind: GitRepository
  #     name: flux-system
  #     namespace: flux-system
  #   interval: 1h
  #   retryInterval: 2m
  #   timeout: 5m
