---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wikijs
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      wikijs:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            envFrom: &envFrom
              - secretRef:
                  name: wikijs-secret
        containers:
          app:
            image:
              repository: ghcr.io/requarks/wiki
              tag: 2
            env:
              - name: DB_TYPE
                value: postgres
              - name: DB_HOST
                secretKeyRef:
                  name: wikijs-secret
                  key: INIT_POSTGRES_HOST
              - name: DB_PORT
                value: 5432
              - name: DB_USER
                secretKeyRef:
                  name: wikijs-secret
                  key: INIT_POSTGRES_USER
              - name: DB_PASS
                secretKeyRef:
                  name: wikijs-secret
                  key: INIT_POSTGRES_PASS
              - name: DB_NAME
                secretKeyRef:
                  name: wikijs-secret
                  key: INIT_POSTGRES_DBNAME
              - name: HA_ACTIVE
                value: true
            securityContext:
              privileged: true
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: wikijs
        ports:
          http:
            port: 3000
    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.jacob-williams.me
        className: internal
        hosts:
          - host: "{{ .Release.Name }}.jacob-williams.me"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
