---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: metrics
  namespace: monitoring
spec:
  datasource:
    url: http://vmsingle-metrics.monitoring.svc:8429
  evaluationInterval: 1m
  externalLabels:
    cluster: vmmetrics
  # extraArgs:
  #   external.url: https://vam.kantai.xyz
  notifiers:
    - url: http://alertmanager.monitoring.svc:9093
  remoteRead:
    url: http://vmsingle-metrics.monitoring.svc:8429
  remoteWrite:
    url: http://vmsingle-metrics.monitoring.svc:8429
  replicaCount: 1
  selectAllByDefault: true
  useDefaultResources: false
  useStrictSecurity: true
