---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: metrics
  namespace: monitoring
spec:
  extraArgs:
    maxLabelsPerTimeseries: "40"
    search.minStalenessInterval: 5m
  replicaCount: 1
  retentionPeriod: "2w"
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 30Gi
    storageClassName: ceph-block
  useDefaultResources: false
  useStrictSecurity: true
