---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stoat
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-labs
        namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      api:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/stoatchat/api
              tag: v0.13.7@sha256:3ffa4e60f655b33bf92b7afb7ba6ef4c9ecadbaa33374c204204c144419c3ac7
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi

      events:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/stoatchat/events
              tag: v0.13.7@sha256:0a8b01998a4d589bb0ab9c2b03ba643aaa654c58287392c12b5cb8fc65aeeb26
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi

      web:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/stoatchat/for-web
              tag: 6c24e46@sha256:66882458b657db03ae24096ca4ae66c4eb44a2ddd6c92fa37c8dbe40ee5c2d55
            env:
              HOSTNAME: https://chat.jacob-williams.me
              REVOLT_PUBLIC_URL: https://chat.jacob-williams.me/api
              VITE_API_URL: https://chat.jacob-williams.me/api
              VITE_WS_URL: wss://chat.jacob-williams.me/ws
              VITE_MEDIA_URL: https://chat.jacob-williams.me/autumn
              VITE_PROXY_URL: https://chat.jacob-williams.me/january
              VITE_CFG_ENABLE_VIDEO: true
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi

      file-server:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/stoatchat/file-server
              tag: v0.13.7@sha256:134ae1b6c5cee73886b0b7068bbef822f74ae0ba66e87f0f183fb5323f4dba80
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi

      proxy:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/stoatchat/proxy
              tag: v0.13.7@sha256:b3e48e0c41f69fe499a9c7c75c4eb6e0b2d415c49ee2b242932584fd61d5cbce
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi

      gifbox:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/stoatchat/gifbox
              tag: v0.13.7@sha256:38d9704d46ddb221b71150f56c32f418422b3ccefbc915e03043e071fefc716e
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi

      crond:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/stoatchat/crond
              tag: v0.13.7@sha256:9e0182cc9cdc61207bc8d55a3354b6f3caf938bab8d7006f2022631183d14eec
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi

      pushd:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/stoatchat/pushd
              tag: v0.13.7@sha256:22f5d056d732c3bbda6343b863eed2c56344559997388cca37a0fd0009131692
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi

      livekit:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/stoatchat/livekit-server
              tag: v1.9.6
            args:
              - "--config"
              - "/etc/livekit.yaml"
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi

    persistence:
      config:
        type: secret
        name: stoat-config
        advancedMounts:
          api:
            app:
              - path: /Revolt.toml
                subPath: Revolt.toml
                readOnly: true
          events:
            app:
              - path: /Revolt.toml
                subPath: Revolt.toml
                readOnly: true
          file-server:
            app:
              - path: /Revolt.toml
                subPath: Revolt.toml
                readOnly: true
          proxy:
            app:
              - path: /Revolt.toml
                subPath: Revolt.toml
                readOnly: true
          gifbox:
            app:
              - path: /Revolt.toml
                subPath: Revolt.toml
                readOnly: true
          crond:
            app:
              - path: /Revolt.toml
                subPath: Revolt.toml
                readOnly: true
          pushd:
            app:
              - path: /Revolt.toml
                subPath: Revolt.toml
                readOnly: true

      livekit-config:
        type: secret
        name: stoat-livekit-config
        advancedMounts:
          livekit:
            app:
              - path: /etc/livekit.yaml
                subPath: livekit.yaml
                readOnly: true

    service:
      api:
        controller: api
        ports:
          http:
            port: 14702
      events:
        controller: events
        ports:
          http:
            port: 14703
      web:
        controller: web
        ports:
          http:
            port: 5000
      file-server:
        controller: file-server
        ports:
          http:
            port: 14704
      proxy:
        controller: proxy
        ports:
          http:
            port: 14705
      gifbox:
        controller: gifbox
        ports:
          http:
            port: 14706
      crond:
        controller: crond
        ports:
          http:
            port: 14707
      pushd:
        controller: pushd
        ports:
          http:
            port: 14708
      livekit:
        controller: livekit
        ports:
          http:
            port: 7880
      livekit-rtc:
        controller: livekit
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 10.0.40.52
        ports:
          rtc-1: {port: 12321, protocol: UDP}
          rtc-2: {port: 12322, protocol: UDP}
          rtc-3: {port: 12323, protocol: UDP}
          rtc-4: {port: 12324, protocol: UDP}
          rtc-5: {port: 12325, protocol: UDP}
          rtc-6: {port: 12326, protocol: UDP}
          rtc-7: {port: 12327, protocol: UDP}
          rtc-8: {port: 12328, protocol: UDP}
          rtc-9: {port: 12329, protocol: UDP}
          rtc-10: {port: 12330, protocol: UDP}
          rtc-11: {port: 12331, protocol: UDP}
          rtc-12: {port: 12332, protocol: UDP}
          rtc-13: {port: 12333, protocol: UDP}
          rtc-14: {port: 12334, protocol: UDP}
          rtc-15: {port: 12335, protocol: UDP}
          rtc-16: {port: 12336, protocol: UDP}
          rtc-17: {port: 12337, protocol: UDP}
          rtc-18: {port: 12338, protocol: UDP}
          rtc-19: {port: 12339, protocol: UDP}
          rtc-20: {port: 12340, protocol: UDP}
