---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stoat
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 5.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-labs
        namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      api:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/stoatchat/api
              tag: v0.15.1@sha256:21d5c842b6182c58df0330e16dff7c234b879e48b3888c12b9836037c91b5314
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi

      events:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/stoatchat/events
              tag: v0.15.3@sha256:3504a540d8f1de0aace13d4b2bd3b1221ee21aeb037fadd0959c85c4a9c920c3
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi

      web:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/stoatchat/for-web
              tag: 6c24e46@sha256:66882458b657db03ae24096ca4ae66c4eb44a2ddd6c92fa37c8dbe40ee5c2d55
            env:
              HOSTNAME: https://chat.jacob-williams.me
              REVOLT_PUBLIC_URL: https://chat.jacob-williams.me/api
              VITE_API_URL: https://chat.jacob-williams.me/api
              VITE_WS_URL: wss://chat.jacob-williams.me/ws
              VITE_MEDIA_URL: https://chat.jacob-williams.me/autumn
              VITE_PROXY_URL: https://chat.jacob-williams.me/january
              VITE_GIFBOX_URL: https://chat.jacob-williams.me/gifbox
              VITE_CFG_ENABLE_VIDEO: true
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi

      file-server:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/stoatchat/file-server
              tag: v0.15.1@sha256:becd5d4bc81b3541cf79b385f6c7c6de7dcbdb2be898a6eb45aea2a5c14df2c4
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi

      proxy:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/stoatchat/proxy
              tag: v0.15.1@sha256:7b4ab6e698490c315e418cfc4d419d5874a662e9246276994305750187b1f2e2
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi

      gifbox:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/stoatchat/gifbox
              tag: v0.15.1@sha256:9dbe75ab2d7986f49ad33d8aafba81bbc15cb123bd820f3faea0033c144561ef
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi

      crond:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/stoatchat/crond
              tag: v0.15.1@sha256:6c419872ed364cd7fb61d2148bc24a93d0427221050db3b4c76957f8bd0e6474
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi

      pushd:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/stoatchat/pushd
              tag: v0.15.1@sha256:e8a4d518df332a79bf958a858555dd12c4d607b53abe80a566e08db98c09f673
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi

      voice-ingress:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/stoatchat/voice-ingress
              tag: v0.15.1@sha256:04b0a44a697f3defebbd2de5fd27314b23b0cc5763ed3171adcbed8364e64461
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi

      livekit:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/stoatchat/livekit-server
              tag: v1.9.14
            args:
              - "--config"
              - "/etc/livekit.yaml"
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi

    persistence:
      config:
        type: secret
        name: stoat-config
        advancedMounts:
          api:
            app:
              - path: /Revolt.toml
                subPath: Revolt.toml
                readOnly: true
          events:
            app:
              - path: /Revolt.toml
                subPath: Revolt.toml
                readOnly: true
          file-server:
            app:
              - path: /Revolt.toml
                subPath: Revolt.toml
                readOnly: true
          proxy:
            app:
              - path: /Revolt.toml
                subPath: Revolt.toml
                readOnly: true
          gifbox:
            app:
              - path: /Revolt.toml
                subPath: Revolt.toml
                readOnly: true
          crond:
            app:
              - path: /Revolt.toml
                subPath: Revolt.toml
                readOnly: true
          pushd:
            app:
              - path: /Revolt.toml
                subPath: Revolt.toml
                readOnly: true
          voice-ingress:
            app:
              - path: /Revolt.toml
                subPath: Revolt.toml
                readOnly: true

      livekit-config:
        type: secret
        name: stoat-livekit-config
        advancedMounts:
          livekit:
            app:
              - path: /etc/livekit.yaml
                subPath: livekit.yaml
                readOnly: true

    service:
      api:
        controller: api
        ports:
          http:
            port: 14702
      events:
        controller: events
        ports:
          http:
            port: 14703
      web:
        controller: web
        ports:
          http:
            port: 5000
      file-server:
        controller: file-server
        ports:
          http:
            port: 14704
      proxy:
        controller: proxy
        ports:
          http:
            port: 14705
      gifbox:
        controller: gifbox
        ports:
          http:
            port: 14706
      crond:
        controller: crond
        ports:
          http:
            port: 14707
      pushd:
        controller: pushd
        ports:
          http:
            port: 14708
      voice-ingress:
        controller: voice-ingress
        ports:
          http:
            port: 8500
      livekit:
        controller: livekit
        ports:
          http:
            port: 7880
      livekit-rtc:
        controller: livekit
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 10.0.40.52
        ports:
          rtc-1: {port: 12321, protocol: UDP}
          rtc-2: {port: 12322, protocol: UDP}
          rtc-3: {port: 12323, protocol: UDP}
          rtc-4: {port: 12324, protocol: UDP}
          rtc-5: {port: 12325, protocol: UDP}
          rtc-6: {port: 12326, protocol: UDP}
          rtc-7: {port: 12327, protocol: UDP}
          rtc-8: {port: 12328, protocol: UDP}
          rtc-9: {port: 12329, protocol: UDP}
          rtc-10: {port: 12330, protocol: UDP}
          rtc-11: {port: 12331, protocol: UDP}
          rtc-12: {port: 12332, protocol: UDP}
          rtc-13: {port: 12333, protocol: UDP}
          rtc-14: {port: 12334, protocol: UDP}
          rtc-15: {port: 12335, protocol: UDP}
          rtc-16: {port: 12336, protocol: UDP}
          rtc-17: {port: 12337, protocol: UDP}
          rtc-18: {port: 12338, protocol: UDP}
          rtc-19: {port: 12339, protocol: UDP}
          rtc-20: {port: 12340, protocol: UDP}
